#!/usr/bin/python
# __author__ = 'rglab'

# This is our defined function for Cheese And Crackers.
def cheese_and_crackers(cheese_count, boxes_of_crackers):
    print "You have %d cheeses!" % cheese_count
    print "You have %d boxes of crackers" % boxes_of_crackers
    print "Man that's enough for a party!"
    print "Get a blanket.\n"

# providing the numbers directly for our defined function
print "We can just give the function numbers directly:"
cheese_and_crackers(20, 30)

# creating two variables for the amount of cheese and crackers
print "OR, we can use variables from our scripts:"
amount_of_cheese = 10
amount_of_crackers = 50

"""applying two different attributes from our defined function
which we call below
"""
cheese_and_crackers(amount_of_cheese, amount_of_crackers)

# doing basic addition to calculate the count.
print "We can even do math inside too:"
cheese_and_crackers(10 + 20, 5 + 6)

# combining math and variables to calculate the amount.
print "And we can combine the two variables and math:"
cheese_and_crackers(amount_of_cheese + 100, amount_of_crackers + 1000)
