#!/usr/bin/python

# This program is designed to count my chickens
print "I will now count my chickens:"

# Counting the hens and the roosters
print "Hens", 25 + 30 / 6
print "Roosters", 100 - 25 * 3 % 4

# Counting the Effs
print "Now I will count the effs:"

print 3 + 2 + 1 - 5 + 4 % 2 - 1 / 4 + 6

# Asking if it the number is true or false
print "Is it true that 3 + 2 < 5 - 7?"

print 3 + 2 < 5 - 7

# Doing the math
print "What is 3 + 2?", 3 + 2
print "What is 5 - 7?", 5 - 7

print "Oh, that's why it's False."

# doing more math here
print "How about some more."

# comparing numbers here now
print "Is it greater?", 5 > -2
print "Is it greater or equal?", 5 >= - 2
print "Is it less or equal?", 5 <= -2
